# Generated by Django 4.2.6 on 2023-11-06 02:22

from django.db import migrations, models
import django.db.models.deletion

def create_initial_platforms_and_genres(apps, schema_editor):
    # Access the models using the historical version of the app registry
    Platform = apps.get_model('gameReview_app', 'Platform')
    Genre = apps.get_model('gameReview_app', 'Genre')

    # Create instances for platforms
    platforms = [
        'PS5', 'XBOX_SERIES_X', 'SWITCH', 'PC', 'PS4','XBOX_ONE', 'PS3', 'XBOX_360', 'WII_U', 'WII',
        'PS2', 'GAMECUBE', 'N64', 'PS1', 'SEGA_GENESIS', 'SNES', 'NES', 'ATARI_2600', 'GAME_BOY', 'SEGA_MASTER_SYSTEM',
        'XBOX', 'SEGA_SATURN', 'SEGA_DREAMCAST', 'SEGA_GAME_GEAR', 'NDS', 'GBC', 'NVB', 
    ]
    for platform in platforms:
        Platform.objects.create(name=platform)

    # Create instances for genres
    genres = [
        'ACTION', 'ADVENTURE' 'RPG', 'STRATEGY', 'SPORTS', 'SIMULATION', 'PUZZLE', 'HORROR', 'SHOOTER', 'PLATFORMER', 
        'RACING', 'FIGHTING', 'MOBA', 'SURVIVAL', 'SANDBOX', 'STEALTH', 'MUSIC', 'EDUCATIONAL', 'OPEN_WORLD', 'OTHER',
    ]
    for genre in genres:
        Genre.objects.create(game_genre=genre)

class Migration(migrations.Migration):

    dependencies = [
        ('gameReview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_ratings', to='gameReview_app.review'),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[...], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_genre', models.CharField(choices=[...], max_length=50)),
            ],
        ),
        # Create initial data
        migrations.RunPython(create_initial_platforms_and_genres),
    ]
