# Generated by Django 4.2.6 on 2023-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameReview_app', '0002_alter_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='game_genre',
            field=models.CharField(choices=[('ACTION', 'Action'), ('ADVENTURE', 'Adventure'), ('EDUCATIONAL', 'Educational'), ('FIGHTING', 'Fighting'), ('HORROR', 'Horror'), ('MOBA', 'MOBA'), ('MUSIC', 'Music'), ('OPEN_WORLD', 'Open World'), ('OTHER', 'Other'), ('PLATFORMER', 'Platformer'), ('PUZZLE', 'Puzzle'), ('RACING', 'Racing'), ('RPG', 'Role-Playing Game'), ('SANDBOX', 'Sandbox'), ('SHOOTER', 'Shooter'), ('SIMULATION', 'Simulation'), ('SPORTS', 'Sports'), ('STEALTH', 'Stealth'), ('STRATEGY', 'Strategy'), ('SURVIVAL', 'Survival')], max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('ATARI_2600', 'Atari 2600'), ('GAMECUBE', 'GameCube'), ('N64', 'Nintendo 64'), ('NDS', 'Nintendo DS'), ('NES', 'Nintendo Entertainment System'), ('GAME_BOY', 'Nintendo Game Boy'), ('GBC', 'Nintendo Game Boy Color'), ('SWITCH', 'Nintendo Switch'), ('NVB', 'Nintendo Virtual Boy'), ('PC', 'PC'), ('PS1', 'PlayStation 1'), ('PS2', 'PlayStation 2'), ('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('SEGA_DREAMCAST', 'Sega Dreamcast'), ('SEGA_GAME_GEAR', 'Sega Game Gear'), ('SEGA_GENESIS', 'Sega Genesis'), ('SEGA_MASTER_SYSTEM', 'Sega Master System'), ('SEGA_SATURN', 'Sega Saturn'), ('SNES', 'Super Nintendo Entertainment System'), ('WII', 'Wii'), ('WII_U', 'Wii U'), ('XBOX', 'XBOX'), ('XBOX_360', 'Xbox 360'), ('XBOX_ONE', 'Xbox One'), ('XBOX_SERIES_X', 'Xbox Series X')], max_length=50),
        ),
    ]
