# Generated by Django 4.2.7 on 2023-11-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameReview_app', '0002_user_is_staff'),
    ]

    operations = [
    ]
