# Generated by Django 4.2.6 on 2023-11-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameReview_app', '0007_auto_20231105_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
